// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuR_d71QJ4jNtgSGQBfwumkJS8WHV_xEA',
    appId: '1:894593598450:web:6015ddf4de43dbfce3a16b',
    messagingSenderId: '894593598450',
    projectId: 'beauty-shop-app-10ec1',
    authDomain: 'beauty-shop-app-10ec1.firebaseapp.com',
    storageBucket: 'beauty-shop-app-10ec1.firebasestorage.app',
    measurementId: 'G-PXMCRMSTKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW9Xd8KesytQ-lbUXNZaYOuKmAUgMF9gg',
    appId: '1:894593598450:android:3e6d7a41fb866dd6e3a16b',
    messagingSenderId: '894593598450',
    projectId: 'beauty-shop-app-10ec1',
    storageBucket: 'beauty-shop-app-10ec1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9mdsWmbvcqzQ5BI2V7qNSsGutvh4d2ik',
    appId: '1:894593598450:ios:04fc441bb443bfbee3a16b',
    messagingSenderId: '894593598450',
    projectId: 'beauty-shop-app-10ec1',
    storageBucket: 'beauty-shop-app-10ec1.firebasestorage.app',
    iosBundleId: 'com.example.giaoDienTrangHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9mdsWmbvcqzQ5BI2V7qNSsGutvh4d2ik',
    appId: '1:894593598450:ios:04fc441bb443bfbee3a16b',
    messagingSenderId: '894593598450',
    projectId: 'beauty-shop-app-10ec1',
    storageBucket: 'beauty-shop-app-10ec1.firebasestorage.app',
    iosBundleId: 'com.example.giaoDienTrangHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuR_d71QJ4jNtgSGQBfwumkJS8WHV_xEA',
    appId: '1:894593598450:web:5a93f4410be3d755e3a16b',
    messagingSenderId: '894593598450',
    projectId: 'beauty-shop-app-10ec1',
    authDomain: 'beauty-shop-app-10ec1.firebaseapp.com',
    storageBucket: 'beauty-shop-app-10ec1.firebasestorage.app',
    measurementId: 'G-LJ7VJJR81K',
  );
}
