final List<Map<String, dynamic>> productList = [
  {
    'id': 'SP001',
    'name': 'Kem chống nắng La Roche-Posay Anthelios',
    'brand': 'La Roche-Posay',
    'type': 'chống nắng',
    'price': 320000,
    'image':
        'https://edbeauty.vn/wp-content/uploads/2024/10/Product-Variation-50-ml-Front.jpg',
    'promotion': 'Tặng 1 gel rửa mặt',
  },
  {
    'id': 'SP002',
    'name': 'Sữa rửa mặt Cetaphil Gentle Skin Cleanser',
    'brand': 'Cetaphil',
    'type': 'sữa rửa mặt',
    'price': 145000,
    'image':
        'https://www.guardian.com.vn/media/catalog/product/cache/30b2b44eba57cd45fd3ef9287600968e/s/u/sua-rua-mat-cetaphil-diu-nhe-khong-xa-phong-moi-3_7e864003c68b42ecb1b42088894cf086_zlktadjrdoqhjwme.jpg',
    'promotion': null,
  },
  {
    'id': 'SP003',
    'name': 'Serum Paula’s Choice BHA 2%',
    'brand': 'Paula’s Choice',
    'type': 'serum',
    'price': 450000,
    'image': 'https://example.com/image003.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP004',
    'name': 'Toner Klairs Supple Preparation',
    'brand': 'Klairs',
    'type': 'toner',
    'price': 280000,
    'image': 'https://example.com/image004.jpg',
    'promotion': null,
  },
  {
    'id': 'SP005',
    'name': 'Kem dưỡng CeraVe Moisturizing Cream',
    'brand': 'CeraVe',
    'type': 'kem dưỡng',
    'price': 310000,
    'image': 'https://example.com/image005.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP006',
    'name': 'Mặt nạ Mediheal Tea Tree',
    'brand': 'Mediheal',
    'type': 'mặt nạ',
    'price': 25000,
    'image': 'https://example.com/image006.jpg',
    'promotion': null,
  },
  {
    'id': 'SP007',
    'name': 'Nước tẩy trang Bioderma Sensibio',
    'brand': 'Bioderma',
    'type': 'tẩy trang',
    'price': 290000,
    'image': 'https://example.com/image007.jpg',
    'promotion': 'Tặng 1 bông tẩy trang',
  },
  {
    'id': 'SP008',
    'name': 'Kem chống nắng Skin1004 Madagascar',
    'brand': 'Skin1004',
    'type': 'chống nắng',
    'price': 265000,
    'image': 'https://example.com/image008.jpg',
    'promotion': null,
  },
  {
    'id': 'SP009',
    'name': 'Sữa rửa mặt Senka Perfect Whip',
    'brand': 'Senka',
    'type': 'sữa rửa mặt',
    'price': 85000,
    'image': 'https://example.com/image009.jpg',
    'promotion': 'Giảm 15%',
  },
  {
    'id': 'SP010',
    'name': 'Serum The Ordinary Niacinamide 10%',
    'brand': 'The Ordinary',
    'type': 'serum',
    'price': 280000,
    'image': 'https://example.com/image010.jpg',
    'promotion': null,
  },
  {
    'id': 'SP011',
    'name': 'Toner Mamonde Rose Water',
    'brand': 'Mamonde',
    'type': 'toner',
    'price': 210000,
    'image': 'https://example.com/image011.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP012',
    'name': 'Kem dưỡng La Roche-Posay Cicaplast',
    'brand': 'La Roche-Posay',
    'type': 'kem dưỡng',
    'price': 340000,
    'image': 'https://example.com/image012.jpg',
    'promotion': null,
  },
  {
    'id': 'SP013',
    'name': 'Mặt nạ Naruko Tea Tree',
    'brand': 'Naruko',
    'type': 'mặt nạ',
    'price': 27000,
    'image': 'https://example.com/image013.jpg',
    'promotion': 'Mua 5 tặng 1',
  },
  {
    'id': 'SP014',
    'name': 'Nước tẩy trang L’Oreal Micellar Water',
    'brand': 'L’Oreal',
    'type': 'tẩy trang',
    'price': 180000,
    'image': 'https://example.com/image014.jpg',
    'promotion': null,
  },
  {
    'id': 'SP015',
    'name': 'Kem chống nắng Anessa Perfect UV',
    'brand': 'Anessa',
    'type': 'chống nắng',
    'price': 420000,
    'image': 'https://example.com/image015.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP016',
    'name': 'Sữa rửa mặt Simple Kind to Skin',
    'brand': 'Simple',
    'type': 'sữa rửa mặt',
    'price': 95000,
    'image': 'https://example.com/image016.jpg',
    'promotion': null,
  },
  {
    'id': 'SP017',
    'name': 'Serum Vichy Mineral 89',
    'brand': 'Vichy',
    'type': 'serum',
    'price': 490000,
    'image': 'https://example.com/image017.jpg',
    'promotion': 'Tặng 1 mini size',
  },
  {
    'id': 'SP018',
    'name': 'Toner Thayers Witch Hazel',
    'brand': 'Thayers',
    'type': 'toner',
    'price': 230000,
    'image': 'https://example.com/image018.jpg',
    'promotion': null,
  },
  {
    'id': 'SP019',
    'name': 'Kem dưỡng Neutrogena Hydro Boost',
    'brand': 'Neutrogena',
    'type': 'kem dưỡng',
    'price': 295000,
    'image': 'https://example.com/image019.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP020',
    'name': 'Mặt nạ Lululun Moisture Rich',
    'brand': 'Lululun',
    'type': 'mặt nạ',
    'price': 30000,
    'image': 'https://example.com/image020.jpg',
    'promotion': null,
  },
  {
    'id': 'SP021',
    'name': 'Toner Innisfree Green Tea Balancing',
    'brand': 'Innisfree',
    'type': 'toner',
    'price': 195000,
    'image': 'https://example.com/image021.jpg',
    'promotion': null,
  },
  {
    'id': 'SP022',
    'name': 'Serum Some By Mi AHA-BHA-PHA 30 Days',
    'brand': 'Some By Mi',
    'type': 'serum',
    'price': 310000,
    'image': 'https://example.com/image022.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP023',
    'name': 'Kem dưỡng Hada Labo Advanced Nourish',
    'brand': 'Hada Labo',
    'type': 'kem dưỡng',
    'price': 220000,
    'image': 'https://example.com/image023.jpg',
    'promotion': null,
  },
  {
    'id': 'SP024',
    'name': 'Mặt nạ Banobagi Vita Genic Jelly',
    'brand': 'Banobagi',
    'type': 'mặt nạ',
    'price': 27000,
    'image': 'https://example.com/image024.jpg',
    'promotion': 'Mua 4 tặng 1',
  },
  {
    'id': 'SP025',
    'name': 'Sữa rửa mặt Cosrx Low pH Good Morning',
    'brand': 'Cosrx',
    'type': 'sữa rửa mặt',
    'price': 145000,
    'image': 'https://example.com/image025.jpg',
    'promotion': null,
  },
  {
    'id': 'SP026',
    'name': 'Kem chống nắng Vichy Capital Soleil',
    'brand': 'Vichy',
    'type': 'chống nắng',
    'price': 365000,
    'image': 'https://example.com/image026.jpg',
    'promotion': 'Tặng 1 sample',
  },
  {
    'id': 'SP027',
    'name': 'Tẩy trang Garnier Micellar Water',
    'brand': 'Garnier',
    'type': 'tẩy trang',
    'price': 165000,
    'image': 'https://example.com/image027.jpg',
    'promotion': null,
  },
  {
    'id': 'SP028',
    'name': 'Serum Timeless Vitamin C + E + Ferulic',
    'brand': 'Timeless',
    'type': 'serum',
    'price': 420000,
    'image': 'https://example.com/image028.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP029',
    'name': 'Toner Evoluderm Lotion Tonique',
    'brand': 'Evoluderm',
    'type': 'toner',
    'price': 99000,
    'image': 'https://example.com/image029.jpg',
    'promotion': null,
  },
  {
    'id': 'SP030',
    'name': 'Kem dưỡng Simple Hydrating Light Moisturizer',
    'brand': 'Simple',
    'type': 'kem dưỡng',
    'price': 125000,
    'image': 'https://example.com/image030.jpg',
    'promotion': 'Tặng 1 khăn lau mặt',
  },
  {
    'id': 'SP031',
    'name': 'Mặt nạ Vedette Clay Mask Aloe Vera',
    'brand': 'Vedette',
    'type': 'mặt nạ',
    'price': 18000,
    'image': 'https://example.com/image031.jpg',
    'promotion': null,
  },
  {
    'id': 'SP032',
    'name': 'Sữa rửa mặt Hatomugi Naturie',
    'brand': 'Naturie',
    'type': 'sữa rửa mặt',
    'price': 98000,
    'image': 'https://example.com/image032.jpg',
    'promotion': 'Mua 2 tặng 1',
  },
  {
    'id': 'SP033',
    'name': 'Kem chống nắng Biore UV Aqua Rich',
    'brand': 'Biore',
    'type': 'chống nắng',
    'price': 210000,
    'image': 'https://example.com/image033.jpg',
    'promotion': null,
  },
  {
    'id': 'SP034',
    'name': 'Tẩy trang Senka All Clear Water',
    'brand': 'Senka',
    'type': 'tẩy trang',
    'price': 135000,
    'image': 'https://example.com/image034.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP035',
    'name': 'Serum L’Oreal Revitalift Hyaluronic Acid',
    'brand': 'L’Oreal',
    'type': 'serum',
    'price': 495000,
    'image': 'https://example.com/image035.jpg',
    'promotion': 'Tặng 1 mặt nạ giấy',
  },
  {
    'id': 'SP036',
    'name': 'Toner Eucerin ProACNE Solution',
    'brand': 'Eucerin',
    'type': 'toner',
    'price': 245000,
    'image': 'https://example.com/image036.jpg',
    'promotion': null,
  },
  {
    'id': 'SP037',
    'name': 'Kem dưỡng The Body Shop Vitamin E',
    'brand': 'The Body Shop',
    'type': 'kem dưỡng',
    'price': 370000,
    'image': 'https://example.com/image037.jpg',
    'promotion': 'Giảm 15%',
  },
  {
    'id': 'SP038',
    'name': 'Mặt nạ My Beauty Diary Black Pearl',
    'brand': 'My Beauty Diary',
    'type': 'mặt nạ',
    'price': 29000,
    'image': 'https://example.com/image038.jpg',
    'promotion': null,
  },
  {
    'id': 'SP039',
    'name': 'Sữa rửa mặt Innisfree Jeju Volcanic Pore',
    'brand': 'Innisfree',
    'type': 'sữa rửa mặt',
    'price': 135000,
    'image': 'https://example.com/image039.jpg',
    'promotion': 'Tặng 1 sample',
  },
  {
    'id': 'SP040',
    'name': 'Kem chống nắng Missha All Around Safe Block',
    'brand': 'Missha',
    'type': 'chống nắng',
    'price': 185000,
    'image': 'https://example.com/image040.jpg',
    'promotion': null,
  },
  {
    'id': 'SP041',
    'name': 'Serum Kiehl’s Clearly Corrective Dark Spot',
    'brand': 'Kiehl’s',
    'type': 'serum',
    'price': 890000,
    'image': 'https://example.com/image041.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP042',
    'name': 'Toner Benton Aloe BHA Skin',
    'brand': 'Benton',
    'type': 'toner',
    'price': 210000,
    'image': 'https://example.com/image042.jpg',
    'promotion': null,
  },
  {
    'id': 'SP043',
    'name': 'Kem dưỡng Laneige Water Bank Blue',
    'brand': 'Laneige',
    'type': 'kem dưỡng',
    'price': 520000,
    'image': 'https://example.com/image043.jpg',
    'promotion': 'Tặng 1 mặt nạ ngủ',
  },
  {
    'id': 'SP044',
    'name': 'Mặt nạ The Face Shop Real Nature',
    'brand': 'The Face Shop',
    'type': 'mặt nạ',
    'price': 25000,
    'image': 'https://example.com/image044.jpg',
    'promotion': 'Mua 10 tặng 2',
  },
  {
    'id': 'SP045',
    'name': 'Sữa rửa mặt Vichy Normaderm Phytosolution',
    'brand': 'Vichy',
    'type': 'sữa rửa mặt',
    'price': 285000,
    'image': 'https://example.com/image045.jpg',
    'promotion': null,
  },
  {
    'id': 'SP046',
    'name': 'Kem chống nắng Eucerin Sun Gel-Cream',
    'brand': 'Eucerin',
    'type': 'chống nắng',
    'price': 395000,
    'image': 'https://example.com/image046.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP047',
    'name': 'Tẩy trang DHC Deep Cleansing Oil',
    'brand': 'DHC',
    'type': 'tẩy trang',
    'price': 320000,
    'image': 'https://example.com/image047.jpg',
    'promotion': null,
  },
  {
    'id': 'SP048',
    'name': 'Serum Estee Lauder Advanced Night Repair',
    'brand': 'Estee Lauder',
    'type': 'serum',
    'price': 1950000,
    'image': 'https://example.com/image048.jpg',
    'promotion': 'Tặng 1 mini size',
  },
  {
    'id': 'SP049',
    'name': 'Toner Labo Labo Super Keana',
    'brand': 'Labo Labo',
    'type': 'toner',
    'price': 295000,
    'image': 'https://example.com/image049.jpg',
    'promotion': null,
  },
  {
    'id': 'SP050',
    'name': 'Kem dưỡng Innisfree Green Tea Seed Cream',
    'brand': 'Innisfree',
    'type': 'kem dưỡng',
    'price': 340000,
    'image': 'https://example.com/image050.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP051',
    'name': 'Mặt nạ SexyLook Black Mask',
    'brand': 'SexyLook',
    'type': 'mặt nạ',
    'price': 28000,
    'image': 'https://example.com/image051.jpg',
    'promotion': null,
  },
  {
    'id': 'SP052',
    'name': 'Sữa rửa mặt The Ordinary Squalane Cleanser',
    'brand': 'The Ordinary',
    'type': 'sữa rửa mặt',
    'price': 220000,
    'image': 'https://example.com/image052.jpg',
    'promotion': 'Tặng 1 khăn lau mặt',
  },
  {
    'id': 'SP053',
    'name': 'Kem chống nắng Klairs Soft Airy UV Essence',
    'brand': 'Klairs',
    'type': 'chống nắng',
    'price': 295000,
    'image': 'https://example.com/image053.jpg',
    'promotion': null,
  },
  {
    'id': 'SP054',
    'name': 'Tẩy trang Neutrogena Oil-Free Eye Makeup Remover',
    'brand': 'Neutrogena',
    'type': 'tẩy trang',
    'price': 185000,
    'image': 'https://example.com/image054.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP055',
    'name': 'Serum Skinceuticals C E Ferulic',
    'brand': 'Skinceuticals',
    'type': 'serum',
    'price': 2950000,
    'image': 'https://example.com/image055.jpg',
    'promotion': 'Tặng 1 mặt nạ cao cấp',
  },
  {
    'id': 'SP056',
    'name': 'Toner Simple Soothing Facial Toner',
    'brand': 'Simple',
    'type': 'toner',
    'price': 115000,
    'image': 'https://example.com/image056.jpg',
    'promotion': null,
  },
  {
    'id': 'SP057',
    'name': 'Kem dưỡng Paula’s Choice Omega+ Complex',
    'brand': 'Paula’s Choice',
    'type': 'kem dưỡng',
    'price': 690000,
    'image': 'https://example.com/image057.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP058',
    'name': 'Mặt nạ LANEIGE Water Sleeping Mask',
    'brand': 'Laneige',
    'type': 'mặt nạ',
    'price': 420000,
    'image': 'https://example.com/image058.jpg',
    'promotion': 'Tặng 1 sample',
  },
  {
    'id': 'SP059',
    'name': 'Sữa rửa mặt SVR Sebiaclear Gel Moussant',
    'brand': 'SVR',
    'type': 'sữa rửa mặt',
    'price': 265000,
    'image': 'https://example.com/image059.jpg',
    'promotion': null,
  },
  {
    'id': 'SP060',
    'name': 'Kem chống nắng Avene Very High Protection',
    'brand': 'Avene',
    'type': 'chống nắng',
    'price': 385000,
    'image': 'https://example.com/image060.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP061',
    'name': 'Serum Garnier Light Complete Vitamin C',
    'brand': 'Garnier',
    'type': 'serum',
    'price': 215000,
    'image': 'https://example.com/image061.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP062',
    'name': 'Toner Hada Labo Gokujyun Premium',
    'brand': 'Hada Labo',
    'type': 'toner',
    'price': 245000,
    'image': 'https://example.com/image062.jpg',
    'promotion': null,
  },
  {
    'id': 'SP063',
    'name': 'Kem dưỡng Olay Regenerist Micro-Sculpting',
    'brand': 'Olay',
    'type': 'kem dưỡng',
    'price': 520000,
    'image': 'https://example.com/image063.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP064',
    'name': 'Mặt nạ Freeman Feeling Beautiful Clay Mask',
    'brand': 'Freeman',
    'type': 'mặt nạ',
    'price': 85000,
    'image': 'https://example.com/image064.jpg',
    'promotion': null,
  },
  {
    'id': 'SP065',
    'name': 'Sữa rửa mặt Pond’s Pure White',
    'brand': 'Pond’s',
    'type': 'sữa rửa mặt',
    'price': 75000,
    'image': 'https://example.com/image065.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP066',
    'name': 'Kem chống nắng The Saem Eco Earth Power',
    'brand': 'The Saem',
    'type': 'chống nắng',
    'price': 175000,
    'image': 'https://example.com/image066.jpg',
    'promotion': null,
  },
  {
    'id': 'SP067',
    'name': 'Tẩy trang Byphasse Solution Micellaire',
    'brand': 'Byphasse',
    'type': 'tẩy trang',
    'price': 125000,
    'image': 'https://example.com/image067.jpg',
    'promotion': 'Tặng 1 bông tẩy trang',
  },
  {
    'id': 'SP068',
    'name': 'Serum L’Oreal Glycolic Bright',
    'brand': 'L’Oreal',
    'type': 'serum',
    'price': 395000,
    'image': 'https://example.com/image068.jpg',
    'promotion': null,
  },
  {
    'id': 'SP069',
    'name': 'Toner Evoluderm Eau Pure',
    'brand': 'Evoluderm',
    'type': 'toner',
    'price': 99000,
    'image': 'https://example.com/image069.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP070',
    'name': 'Kem dưỡng Pond’s Age Miracle',
    'brand': 'Pond’s',
    'type': 'kem dưỡng',
    'price': 295000,
    'image': 'https://example.com/image070.jpg',
    'promotion': null,
  },
  {
    'id': 'SP071',
    'name': 'Mặt nạ Innisfree My Real Squeeze Mask',
    'brand': 'Innisfree',
    'type': 'mặt nạ',
    'price': 25000,
    'image': 'https://example.com/image071.jpg',
    'promotion': 'Mua 5 tặng 1',
  },
  {
    'id': 'SP072',
    'name': 'Sữa rửa mặt Clean & Clear Foaming',
    'brand': 'Clean & Clear',
    'type': 'sữa rửa mặt',
    'price': 65000,
    'image': 'https://example.com/image072.jpg',
    'promotion': null,
  },
  {
    'id': 'SP073',
    'name': 'Kem chống nắng Sunplay Skin Aqua',
    'brand': 'Sunplay',
    'type': 'chống nắng',
    'price': 145000,
    'image': 'https://example.com/image073.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP074',
    'name': 'Tẩy trang Nivea MicellAIR Skin Breathe',
    'brand': 'Nivea',
    'type': 'tẩy trang',
    'price': 135000,
    'image': 'https://example.com/image074.jpg',
    'promotion': null,
  },
  {
    'id': 'SP075',
    'name': 'Serum Rohto Melano CC',
    'brand': 'Rohto',
    'type': 'serum',
    'price': 295000,
    'image': 'https://example.com/image075.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP076',
    'name': 'Toner The Ordinary Glycolic Acid 7%',
    'brand': 'The Ordinary',
    'type': 'toner',
    'price': 295000,
    'image': 'https://example.com/image076.jpg',
    'promotion': null,
  },
  {
    'id': 'SP077',
    'name': 'Kem dưỡng Vaseline Healthy White',
    'brand': 'Vaseline',
    'type': 'kem dưỡng',
    'price': 115000,
    'image': 'https://example.com/image077.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP078',
    'name': 'Mặt nạ Lush Mask of Magnaminty',
    'brand': 'Lush',
    'type': 'mặt nạ',
    'price': 420000,
    'image': 'https://example.com/image078.jpg',
    'promotion': null,
  },
  {
    'id': 'SP079',
    'name': 'Sữa rửa mặt Acnes Creamy Wash',
    'brand': 'Acnes',
    'type': 'sữa rửa mặt',
    'price': 65000,
    'image': 'https://example.com/image079.jpg',
    'promotion': 'Mua 2 tặng 1',
  },
  {
    'id': 'SP080',
    'name': 'Kem chống nắng Cell Fusion C Laser Sunscreen',
    'brand': 'Cell Fusion C',
    'type': 'chống nắng',
    'price': 395000,
    'image': 'https://example.com/image080.jpg',
    'promotion': null,
  },
  {
    'id': 'SP081',
    'name': 'Serum Innisfree Brightening Pore',
    'brand': 'Innisfree',
    'type': 'serum',
    'price': 420000,
    'image': 'https://example.com/image081.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP082',
    'name': 'Toner Cosrx Centella Water Alcohol-Free',
    'brand': 'Cosrx',
    'type': 'toner',
    'price': 245000,
    'image': 'https://example.com/image082.jpg',
    'promotion': null,
  },
  {
    'id': 'SP083',
    'name': 'Kem dưỡng SVR Hydraliane Riche',
    'brand': 'SVR',
    'type': 'kem dưỡng',
    'price': 395000,
    'image': 'https://example.com/image083.jpg',
    'promotion': 'Tặng 1 sample',
  },
  {
    'id': 'SP084',
    'name': 'Mặt nạ Dr.Jart+ Dermask Water Jet',
    'brand': 'Dr.Jart+',
    'type': 'mặt nạ',
    'price': 32000,
    'image': 'https://example.com/image084.jpg',
    'promotion': null,
  },
  {
    'id': 'SP085',
    'name': 'Sữa rửa mặt La Roche-Posay Effaclar',
    'brand': 'La Roche-Posay',
    'type': 'sữa rửa mặt',
    'price': 295000,
    'image': 'https://example.com/image085.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP086',
    'name': 'Kem chống nắng The Ordinary Mineral UV Filters',
    'brand': 'The Ordinary',
    'type': 'chống nắng',
    'price': 310000,
    'image': 'https://example.com/image086.jpg',
    'promotion': null,
  },
  {
    'id': 'SP087',
    'name': 'Tẩy trang Garnier Micellar Oil-Infused',
    'brand': 'Garnier',
    'type': 'tẩy trang',
    'price': 155000,
    'image': 'https://example.com/image087.jpg',
    'promotion': 'Tặng 1 bông tẩy trang',
  },
  {
    'id': 'SP088',
    'name': 'Serum Klairs Freshly Juiced Vitamin Drop',
    'brand': 'Klairs',
    'type': 'serum',
    'price': 295000,
    'image': 'https://example.com/image088.jpg',
    'promotion': null,
  },
  {
    'id': 'SP089',
    'name': 'Toner Mamonde Pore Clean',
    'brand': 'Mamonde',
    'type': 'toner',
    'price': 215000,
    'image': 'https://example.com/image089.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP090',
    'name': 'Kem dưỡng Neutrogena Bright Boost',
    'brand': 'Neutrogena',
    'type': 'kem dưỡng',
    'price': 365000,
    'image': 'https://example.com/image090.jpg',
    'promotion': null,
  },
  {
    'id': 'SP091',
    'name': 'Mặt nạ Mediheal N.M.F Aquaring Ampoule',
    'brand': 'Mediheal',
    'type': 'mặt nạ',
    'price': 27000,
    'image': 'https://example.com/image091.jpg',
    'promotion': 'Mua 10 tặng 2',
  },
  {
    'id': 'SP092',
    'name': 'Sữa rửa mặt CeraVe Foaming Cleanser',
    'brand': 'CeraVe',
    'type': 'sữa rửa mặt',
    'price': 295000,
    'image': 'https://example.com/image092.jpg',
    'promotion': null,
  },
  {
    'id': 'SP093',
    'name': 'Kem chống nắng Biore UV Perfect Milk',
    'brand': 'Biore',
    'type': 'chống nắng',
    'price': 165000,
    'image': 'https://example.com/image093.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP094',
    'name': 'Tẩy trang L’Oreal Micellar Water Moisturizing',
    'brand': 'L’Oreal',
    'type': 'tẩy trang',
    'price': 145000,
    'image': 'https://example.com/image094.jpg',
    'promotion': null,
  },
  {
    'id': 'SP095',
    'name': 'Serum The Inkey List Hyaluronic Acid',
    'brand': 'The Inkey List',
    'type': 'serum',
    'price': 295000,
    'image': 'https://example.com/image095.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP096',
    'name': 'Toner Thayers Rose Petal',
    'brand': 'Thayers',
    'type': 'toner',
    'price': 230000,
    'image': 'https://example.com/image096.jpg',
    'promotion': null,
  },
  {
    'id': 'SP097',
    'name': 'Kem dưỡng Cetaphil Moisturizing Cream',
    'brand': 'Cetaphil',
    'type': 'kem dưỡng',
    'price': 295000,
    'image': 'https://example.com/image097.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP098',
    'name': 'Mặt nạ Naruko Rose & Botanic HA Aqua',
    'brand': 'Naruko',
    'type': 'mặt nạ',
    'price': 29000,
    'image': 'https://example.com/image098.jpg',
    'promotion': null,
  },
  {
    'id': 'SP099',
    'name': 'Sữa rửa mặt Senka Perfect Whip Collagen',
    'brand': 'Senka',
    'type': 'sữa rửa mặt',
    'price': 95000,
    'image': 'https://example.com/image099.jpg',
    'promotion': 'Mua 2 tặng 1',
  },
  {
    'id': 'SP100',
    'name': 'Kem chống nắng Vichy Ideal Soleil',
    'brand': 'Vichy',
    'type': 'chống nắng',
    'price': 420000,
    'image': 'https://example.com/image100.jpg',
    'promotion': null,
  },
  {
    'id': 'SP101',
    'name': 'Serum Vichy Liftactiv Supreme',
    'brand': 'Vichy',
    'type': 'serum',
    'price': 890000,
    'image': 'https://example.com/image101.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP102',
    'name': 'Toner Kiehl’s Calendula Herbal Extract',
    'brand': 'Kiehl’s',
    'type': 'toner',
    'price': 720000,
    'image': 'https://example.com/image102.jpg',
    'promotion': null,
  },
  {
    'id': 'SP103',
    'name': 'Kem dưỡng L’Oreal Paris Revitalift',
    'brand': 'L’Oreal',
    'type': 'kem dưỡng',
    'price': 495000,
    'image': 'https://example.com/image103.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP104',
    'name': 'Mặt nạ Laneige Cica Sleeping Mask',
    'brand': 'Laneige',
    'type': 'mặt nạ',
    'price': 420000,
    'image': 'https://example.com/image104.jpg',
    'promotion': null,
  },
  {
    'id': 'SP105',
    'name': 'Sữa rửa mặt Bioderma Sebium Gel Moussant',
    'brand': 'Bioderma',
    'type': 'sữa rửa mặt',
    'price': 265000,
    'image': 'https://example.com/image105.jpg',
    'promotion': 'Tặng 1 khăn lau mặt',
  },
  {
    'id': 'SP106',
    'name': 'Kem chống nắng Anessa Whitening UV Sunscreen',
    'brand': 'Anessa',
    'type': 'chống nắng',
    'price': 495000,
    'image': 'https://example.com/image106.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP107',
    'name': 'Tẩy trang Simple Micellar Cleansing Water',
    'brand': 'Simple',
    'type': 'tẩy trang',
    'price': 135000,
    'image': 'https://example.com/image107.jpg',
    'promotion': null,
  },
  {
    'id': 'SP108',
    'name': 'Serum Paula’s Choice Niacinamide Booster',
    'brand': 'Paula’s Choice',
    'type': 'serum',
    'price': 890000,
    'image': 'https://example.com/image108.jpg',
    'promotion': 'Tặng 1 mini size',
  },
  {
    'id': 'SP109',
    'name': 'Toner Klairs Daily Skin Hydrating',
    'brand': 'Klairs',
    'type': 'toner',
    'price': 295000,
    'image': 'https://example.com/image109.jpg',
    'promotion': null,
  },
  {
    'id': 'SP110',
    'name': 'Kem dưỡng The Ordinary Natural Moisturizing Factors',
    'brand': 'The Ordinary',
    'type': 'kem dưỡng',
    'price': 295000,
    'image': 'https://example.com/image110.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP111',
    'name': 'Mặt nạ Lululun Precious Red',
    'brand': 'Lululun',
    'type': 'mặt nạ',
    'price': 32000,
    'image': 'https://example.com/image111.jpg',
    'promotion': null,
  },
  {
    'id': 'SP112',
    'name': 'Sữa rửa mặt Eucerin ProACNE Solution',
    'brand': 'Eucerin',
    'type': 'sữa rửa mặt',
    'price': 285000,
    'image': 'https://example.com/image112.jpg',
    'promotion': 'Tặng 1 sample',
  },
  {
    'id': 'SP113',
    'name': 'Kem chống nắng Skin1004 Hyalu-Cica Water-Fit',
    'brand': 'Skin1004',
    'type': 'chống nắng',
    'price': 265000,
    'image': 'https://example.com/image113.jpg',
    'promotion': null,
  },
  {
    'id': 'SP114',
    'name': 'Tẩy trang Bioderma Hydrabio H2O',
    'brand': 'Bioderma',
    'type': 'tẩy trang',
    'price': 290000,
    'image': 'https://example.com/image114.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP115',
    'name': 'Serum Timeless Matrixyl Synthe 6',
    'brand': 'Timeless',
    'type': 'serum',
    'price': 420000,
    'image': 'https://example.com/image115.jpg',
    'promotion': null,
  },
  {
    'id': 'SP116',
    'name': 'Toner Evoluderm Rose Water',
    'brand': 'Evoluderm',
    'type': 'toner',
    'price': 99000,
    'image': 'https://example.com/image116.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP117',
    'name': 'Kem dưỡng CeraVe PM Facial Moisturizing Lotion',
    'brand': 'CeraVe',
    'type': 'kem dưỡng',
    'price': 310000,
    'image': 'https://example.com/image117.jpg',
    'promotion': null,
  },
  {
    'id': 'SP118',
    'name': 'Mặt nạ Vedette Clay Mask Strawberry',
    'brand': 'Vedette',
    'type': 'mặt nạ',
    'price': 18000,
    'image': 'https://example.com/image118.jpg',
    'promotion': 'Mua 3 tặng 1',
  },
  {
    'id': 'SP119',
    'name': 'Sữa rửa mặt Innisfree Bija Trouble Facial Foam',
    'brand': 'Innisfree',
    'type': 'sữa rửa mặt',
    'price': 135000,
    'image': 'https://example.com/image119.jpg',
    'promotion': null,
  },
  {
    'id': 'SP120',
    'name': 'Kem chống nắng Missha Essence Sun Milk',
    'brand': 'Missha',
    'type': 'chống nắng',
    'price': 185000,
    'image': 'https://example.com/image120.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP121',
    'name': 'Serum Some By Mi Snail Truecica',
    'brand': 'Some By Mi',
    'type': 'serum',
    'price': 295000,
    'image': 'https://example.com/image121.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP122',
    'name': 'Toner Rohto Melano CC',
    'brand': 'Rohto',
    'type': 'toner',
    'price': 215000,
    'image': 'https://example.com/image122.jpg',
    'promotion': null,
  },
  {
    'id': 'SP123',
    'name': 'Kem dưỡng Vaseline Intensive Care',
    'brand': 'Vaseline',
    'type': 'kem dưỡng',
    'price': 115000,
    'image': 'https://example.com/image123.jpg',
    'promotion': 'Tặng 1 khăn lau mặt',
  },
  {
    'id': 'SP124',
    'name': 'Mặt nạ Banobagi Vita Cocktail Brightening',
    'brand': 'Banobagi',
    'type': 'mặt nạ',
    'price': 27000,
    'image': 'https://example.com/image124.jpg',
    'promotion': null,
  },
  {
    'id': 'SP125',
    'name': 'Sữa rửa mặt Hada Labo Perfect White',
    'brand': 'Hada Labo',
    'type': 'sữa rửa mặt',
    'price': 98000,
    'image': 'https://example.com/image125.jpg',
    'promotion': 'Mua 2 tặng 1',
  },
  {
    'id': 'SP126',
    'name': 'Kem chống nắng Biore UV Aqua Rich Watery Essence',
    'brand': 'Biore',
    'type': 'chống nắng',
    'price': 210000,
    'image': 'https://example.com/image126.jpg',
    'promotion': null,
  },
  {
    'id': 'SP127',
    'name': 'Tẩy trang Senka Perfect Clear Cleanse',
    'brand': 'Senka',
    'type': 'tẩy trang',
    'price': 135000,
    'image': 'https://example.com/image127.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP128',
    'name': 'Serum The Ordinary Alpha Arbutin 2%',
    'brand': 'The Ordinary',
    'type': 'serum',
    'price': 295000,
    'image': 'https://example.com/image128.jpg',
    'promotion': null,
  },
  {
    'id': 'SP129',
    'name': 'Toner Benton Deep Green Tea',
    'brand': 'Benton',
    'type': 'toner',
    'price': 210000,
    'image': 'https://example.com/image129.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP130',
    'name': 'Kem dưỡng Laneige Water Bank Hydro Cream',
    'brand': 'Laneige',
    'type': 'kem dưỡng',
    'price': 520000,
    'image': 'https://example.com/image130.jpg',
    'promotion': null,
  },
  {
    'id': 'SP131',
    'name': 'Mặt nạ The Face Shop Real Nature Avocado',
    'brand': 'The Face Shop',
    'type': 'mặt nạ',
    'price': 25000,
    'image': 'https://example.com/image131.jpg',
    'promotion': 'Mua 10 tặng 2',
  },
  {
    'id': 'SP132',
    'name': 'Sữa rửa mặt Cosrx Salicylic Acid Daily Gentle Cleanser',
    'brand': 'Cosrx',
    'type': 'sữa rửa mặt',
    'price': 145000,
    'image': 'https://example.com/image132.jpg',
    'promotion': null,
  },
  {
    'id': 'SP133',
    'name': 'Kem chống nắng Klairs Mid-Day Blue Sun Lotion',
    'brand': 'Klairs',
    'type': 'chống nắng',
    'price': 295000,
    'image': 'https://example.com/image133.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP134',
    'name': 'Tẩy trang DHC Olive Virgin Oil',
    'brand': 'DHC',
    'type': 'tẩy trang',
    'price': 320000,
    'image': 'https://example.com/image134.jpg',
    'promotion': null,
  },
  {
    'id': 'SP135',
    'name': 'Serum Estee Lauder Perfectionist Pro',
    'brand': 'Estee Lauder',
    'type': 'serum',
    'price': 1950000,
    'image': 'https://example.com/image135.jpg',
    'promotion': 'Tặng 1 mini size',
  },
  {
    'id': 'SP136',
    'name': 'Toner Labo Labo Keana Lotion',
    'brand': 'Labo Labo',
    'type': 'toner',
    'price': 295000,
    'image': 'https://example.com/image136.jpg',
    'promotion': null,
  },
  {
    'id': 'SP137',
    'name': 'Kem dưỡng Innisfree Jeju Cherry Blossom',
    'brand': 'Innisfree',
    'type': 'kem dưỡng',
    'price': 340000,
    'image': 'https://example.com/image137.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP138',
    'name': 'Mặt nạ SexyLook Hyaluronic Acid',
    'brand': 'SexyLook',
    'type': 'mặt nạ',
    'price': 28000,
    'image': 'https://example.com/image138.jpg',
    'promotion': null,
  },
  {
    'id': 'SP139',
    'name': 'Sữa rửa mặt The Ordinary Glucoside Foaming Cleanser',
    'brand': 'The Ordinary',
    'type': 'sữa rửa mặt',
    'price': 220000,
    'image': 'https://example.com/image139.jpg',
    'promotion': 'Tặng 1 khăn lau mặt',
  },
  {
    'id': 'SP140',
    'name': 'Kem chống nắng Avene Cleanance Sunscreen SPF50+',
    'brand': 'Avene',
    'type': 'chống nắng',
    'price': 385000,
    'image': 'https://example.com/image140.jpg',
    'promotion': null,
  },
  {
    'id': 'SP141',
    'name': 'Serum Skinceuticals Hydrating B5 Gel',
    'brand': 'Skinceuticals',
    'type': 'serum',
    'price': 2950000,
    'image': 'https://example.com/image141.jpg',
    'promotion': 'Tặng 1 mặt nạ cao cấp',
  },
  {
    'id': 'SP142',
    'name': 'Toner Simple Kind to Skin',
    'brand': 'Simple',
    'type': 'toner',
    'price': 115000,
    'image': 'https://example.com/image142.jpg',
    'promotion': null,
  },
  {
    'id': 'SP143',
    'name': 'Kem dưỡng Paula’s Choice Clear Oil-Free Moisturizer',
    'brand': 'Paula’s Choice',
    'type': 'kem dưỡng',
    'price': 690000,
    'image': 'https://example.com/image143.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP144',
    'name': 'Mặt nạ LANEIGE Lip Sleeping Mask',
    'brand': 'Laneige',
    'type': 'mặt nạ',
    'price': 420000,
    'image': 'https://example.com/image144.jpg',
    'promotion': 'Tặng 1 sample',
  },
  {
    'id': 'SP145',
    'name': 'Sữa rửa mặt SVR Topialyse Gel Lavant',
    'brand': 'SVR',
    'type': 'sữa rửa mặt',
    'price': 265000,
    'image': 'https://example.com/image145.jpg',
    'promotion': null,
  },
  {
    'id': 'SP146',
    'name': 'Kem chống nắng Cell Fusion C Toning Sunscreen',
    'brand': 'Cell Fusion C',
    'type': 'chống nắng',
    'price': 395000,
    'image': 'https://example.com/image146.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP147',
    'name': 'Serum Garnier Bright Complete Vitamin C',
    'brand': 'Garnier',
    'type': 'serum',
    'price': 215000,
    'image': 'https://example.com/image147.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP148',
    'name': 'Toner Hada Labo Advanced Nourish',
    'brand': 'Hada Labo',
    'type': 'toner',
    'price': 245000,
    'image': 'https://example.com/image148.jpg',
    'promotion': null,
  },
  {
    'id': 'SP149',
    'name': 'Kem dưỡng Olay Total Effects 7 in One',
    'brand': 'Olay',
    'type': 'kem dưỡng',
    'price': 520000,
    'image': 'https://example.com/image149.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP150',
    'name': 'Mặt nạ Freeman Charcoal & Black Sugar',
    'brand': 'Freeman',
    'type': 'mặt nạ',
    'price': 85000,
    'image': 'https://example.com/image150.jpg',
    'promotion': null,
  },
  {
    'id': 'SP151',
    'name': 'Sữa rửa mặt Pond’s White Beauty',
    'brand': 'Pond’s',
    'type': 'sữa rửa mặt',
    'price': 75000,
    'image': 'https://example.com/image151.jpg',
    'promotion': 'Mua 2 tặng 1',
  },
  {
    'id': 'SP152',
    'name': 'Kem chống nắng The Saem Eco Earth Pink Sun',
    'brand': 'The Saem',
    'type': 'chống nắng',
    'price': 175000,
    'image': 'https://example.com/image152.jpg',
    'promotion': null,
  },
  {
    'id': 'SP153',
    'name': 'Tẩy trang Byphasse Micellar Solution',
    'brand': 'Byphasse',
    'type': 'tẩy trang',
    'price': 125000,
    'image': 'https://example.com/image153.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP154',
    'name': 'Serum L’Oreal Revitalift 1.5% Hyaluronic Acid',
    'brand': 'L’Oreal',
    'type': 'serum',
    'price': 395000,
    'image': 'https://example.com/image154.jpg',
    'promotion': null,
  },
  {
    'id': 'SP155',
    'name': 'Toner Evoluderm Purifying Lotion',
    'brand': 'Evoluderm',
    'type': 'toner',
    'price': 99000,
    'image': 'https://example.com/image155.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP156',
    'name': 'Kem dưỡng Pond’s Flawless Radiance',
    'brand': 'Pond’s',
    'type': 'kem dưỡng',
    'price': 295000,
    'image': 'https://example.com/image156.jpg',
    'promotion': null,
  },
  {
    'id': 'SP157',
    'name': 'Mặt nạ Innisfree Super Volcanic Pore Clay',
    'brand': 'Innisfree',
    'type': 'mặt nạ',
    'price': 25000,
    'image': 'https://example.com/image157.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP158',
    'name': 'Sữa rửa mặt Clean & Clear Morning Energy',
    'brand': 'Clean & Clear',
    'type': 'sữa rửa mặt',
    'price': 65000,
    'image': 'https://example.com/image158.jpg',
    'promotion': null,
  },
  {
    'id': 'SP159',
    'name': 'Kem chống nắng Sunplay Skin Aqua Tone Up',
    'brand': 'Sunplay',
    'type': 'chống nắng',
    'price': 145000,
    'image': 'https://example.com/image159.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP160',
    'name': 'Tẩy trang Nivea Extra White MicellAIR',
    'brand': 'Nivea',
    'type': 'tẩy trang',
    'price': 135000,
    'image': 'https://example.com/image160.jpg',
    'promotion': null,
  },
  {
    'id': 'SP161',
    'name': 'Serum Rohto Melano CC Intensive Anti-Spot',
    'brand': 'Rohto',
    'type': 'serum',
    'price': 295000,
    'image': 'https://example.com/image161.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP162',
    'name': 'Toner The Ordinary Salicylic Acid 2%',
    'brand': 'The Ordinary',
    'type': 'toner',
    'price': 295000,
    'image': 'https://example.com/image162.jpg',
    'promotion': null,
  },
  {
    'id': 'SP163',
    'name': 'Kem dưỡng Vaseline Gluta-Hya Dewy Radiance',
    'brand': 'Vaseline',
    'type': 'kem dưỡng',
    'price': 115000,
    'image': 'https://example.com/image163.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP164',
    'name': 'Mặt nạ Lush Cup O’ Coffee',
    'brand': 'Lush',
    'type': 'mặt nạ',
    'price': 420000,
    'image': 'https://example.com/image164.jpg',
    'promotion': null,
  },
  {
    'id': 'SP165',
    'name': 'Sữa rửa mặt Acnes Anti-Acne Cleanser',
    'brand': 'Acnes',
    'type': 'sữa rửa mặt',
    'price': 65000,
    'image': 'https://example.com/image165.jpg',
    'promotion': 'Mua 2 tặng 1',
  },
  {
    'id': 'SP166',
    'name': 'Kem chống nắng Cell Fusion C Clear Sunscreen',
    'brand': 'Cell Fusion C',
    'type': 'chống nắng',
    'price': 395000,
    'image': 'https://example.com/image166.jpg',
    'promotion': null,
  },
  {
    'id': 'SP167',
    'name': 'Serum Innisfree Green Tea Seed',
    'brand': 'Innisfree',
    'type': 'serum',
    'price': 420000,
    'image': 'https://example.com/image167.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP168',
    'name': 'Toner Cosrx AHA/BHA Clarifying Treatment',
    'brand': 'Cosrx',
    'type': 'toner',
    'price': 245000,
    'image': 'https://example.com/image168.jpg',
    'promotion': null,
  },
  {
    'id': 'SP169',
    'name': 'Kem dưỡng SVR Sebiaclear Hydra',
    'brand': 'SVR',
    'type': 'kem dưỡng',
    'price': 395000,
    'image': 'https://example.com/image169.jpg',
    'promotion': 'Tặng 1 sample',
  },
  {
    'id': 'SP170',
    'name': 'Mặt nạ Dr.Jart+ Cicapair Calming Mask',
    'brand': 'Dr.Jart+',
    'type': 'mặt nạ',
    'price': 32000,
    'image': 'https://example.com/image170.jpg',
    'promotion': null,
  },
  {
    'id': 'SP171',
    'name': 'Sữa rửa mặt La Roche-Posay Toleriane',
    'brand': 'La Roche-Posay',
    'type': 'sữa rửa mặt',
    'price': 295000,
    'image': 'https://example.com/image171.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP172',
    'name': 'Kem chống nắng The Ordinary SPF 30',
    'brand': 'The Ordinary',
    'type': 'chống nắng',
    'price': 310000,
    'image': 'https://example.com/image172.jpg',
    'promotion': null,
  },
  {
    'id': 'SP173',
    'name': 'Tẩy trang Garnier Micellar Rose Water',
    'brand': 'Garnier',
    'type': 'tẩy trang',
    'price': 155000,
    'image': 'https://example.com/image173.jpg',
    'promotion': 'Tặng 1 bông tẩy trang',
  },
  {
    'id': 'SP174',
    'name': 'Serum Klairs Rich Moist Soothing',
    'brand': 'Klairs',
    'type': 'serum',
    'price': 295000,
    'image': 'https://example.com/image174.jpg',
    'promotion': null,
  },
  {
    'id': 'SP175',
    'name': 'Toner Mamonde Chamomile Pure',
    'brand': 'Mamonde',
    'type': 'toner',
    'price': 215000,
    'image': 'https://example.com/image175.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP176',
    'name': 'Kem dưỡng Neutrogena Rapid Wrinkle Repair',
    'brand': 'Neutrogena',
    'type': 'kem dưỡng',
    'price': 365000,
    'image': 'https://example.com/image176.jpg',
    'promotion': null,
  },
  {
    'id': 'SP177',
    'name': 'Mặt nạ Mediheal Collagen Impact',
    'brand': 'Mediheal',
    'type': 'mặt nạ',
    'price': 27000,
    'image': 'https://example.com/image177.jpg',
    'promotion': 'Mua 10 tặng 2',
  },
  {
    'id': 'SP178',
    'name': 'Sữa rửa mặt CeraVe Hydrating Cleanser',
    'brand': 'CeraVe',
    'type': 'sữa rửa mặt',
    'price': 295000,
    'image': 'https://example.com/image178.jpg',
    'promotion': null,
  },
  {
    'id': 'SP179',
    'name': 'Kem chống nắng Biore UV Bright Milk',
    'brand': 'Biore',
    'type': 'chống nắng',
    'price': 165000,
    'image': 'https://example.com/image179.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP180',
    'name': 'Tẩy trang L’Oreal Micellar Water Refreshing',
    'brand': 'L’Oreal',
    'type': 'tẩy trang',
    'price': 145000,
    'image': 'https://example.com/image180.jpg',
    'promotion': null,
  },
  {
    'id': 'SP181',
    'name': 'Serum The Inkey List Retinol',
    'brand': 'The Inkey List',
    'type': 'serum',
    'price': 295000,
    'image': 'https://example.com/image181.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP182',
    'name': 'Toner Thayers Cucumber',
    'brand': 'Thayers',
    'type': 'toner',
    'price': 230000,
    'image': 'https://example.com/image182.jpg',
    'promotion': null,
  },
  {
    'id': 'SP183',
    'name': 'Kem dưỡng Cetaphil Daily Hydrating Lotion',
    'brand': 'Cetaphil',
    'type': 'kem dưỡng',
    'price': 295000,
    'image': 'https://example.com/image183.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP184',
    'name': 'Mặt nạ Naruko Raw Job’s Tears',
    'brand': 'Naruko',
    'type': 'mặt nạ',
    'price': 29000,
    'image': 'https://example.com/image184.jpg',
    'promotion': null,
  },
  {
    'id': 'SP185',
    'name': 'Sữa rửa mặt Senka Speedy Perfect Whip',
    'brand': 'Senka',
    'type': 'sữa rửa mặt',
    'price': 95000,
    'image': 'https://example.com/image185.jpg',
    'promotion': 'Mua 2 tặng 1',
  },
  {
    'id': 'SP186',
    'name': 'Kem chống nắng Vichy Capital Soleil SPF50',
    'brand': 'Vichy',
    'type': 'chống nắng',
    'price': 420000,
    'image': 'https://example.com/image186.jpg',
    'promotion': null,
  },
  {
    'id': 'SP187',
    'name': 'Serum Kiehl’s Hydro-Plumping Re-Texturizing',
    'brand': 'Kiehl’s',
    'type': 'serum',
    'price': 890000,
    'image': 'https://example.com/image187.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP188',
    'name': 'Toner Benton Honest TT Mist',
    'brand': 'Benton',
    'type': 'toner',
    'price': 210000,
    'image': 'https://example.com/image188.jpg',
    'promotion': null,
  },
  {
    'id': 'SP189',
    'name': 'Kem dưỡng L’Oreal Paris White Perfect',
    'brand': 'L’Oreal',
    'type': 'kem dưỡng',
    'price': 495000,
    'image': 'https://example.com/image189.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP190',
    'name': 'Mặt nạ Laneige Water Sleeping Mask Lavender',
    'brand': 'Laneige',
    'type': 'mặt nạ',
    'price': 420000,
    'image': 'https://example.com/image190.jpg',
    'promotion': null,
  },
  {
    'id': 'SP191',
    'name': 'Sữa rửa mặt Bioderma Sensibio Gel Moussant',
    'brand': 'Bioderma',
    'type': 'sữa rửa mặt',
    'price': 265000,
    'image': 'https://example.com/image191.jpg',
    'promotion': 'Tặng 1 khăn lau mặt',
  },
  {
    'id': 'SP192',
    'name': 'Kem chống nắng Anessa Perfect UV Mild Milk',
    'brand': 'Anessa',
    'type': 'chống nắng',
    'price': 495000,
    'image': 'https://example.com/image192.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP192',
    'name': 'Kem chống nắng Anessa Perfect UV Mild Milk',
    'brand': 'Anessa',
    'type': 'chống nắng',
    'price': 495000,
    'image': 'https://example.com/image192.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP193',
    'name': 'Serum Kiehl’s Midnight Recovery Concentrate',
    'brand': 'Kiehl’s',
    'type': 'serum',
    'price': 890000,
    'image': 'https://example.com/image193.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP194',
    'name': 'Toner Benton Aloe BHA',
    'brand': 'Benton',
    'type': 'toner',
    'price': 210000,
    'image': 'https://example.com/image194.jpg',
    'promotion': null,
  },
  {
    'id': 'SP195',
    'name': 'Kem dưỡng L’Oreal Paris Age Perfect',
    'brand': 'L’Oreal',
    'type': 'kem dưỡng',
    'price': 495000,
    'image': 'https://example.com/image195.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP196',
    'name': 'Mặt nạ Laneige Water Sleeping Mask Lavender',
    'brand': 'Laneige',
    'type': 'mặt nạ',
    'price': 420000,
    'image': 'https://example.com/image196.jpg',
    'promotion': null,
  },
  {
    'id': 'SP197',
    'name': 'Sữa rửa mặt Bioderma Sensibio Gel Moussant',
    'brand': 'Bioderma',
    'type': 'sữa rửa mặt',
    'price': 265000,
    'image': 'https://example.com/image197.jpg',
    'promotion': 'Tặng 1 khăn lau mặt',
  },
  {
    'id': 'SP198',
    'name': 'Kem chống nắng Anessa Perfect UV Sunscreen Aqua Booster',
    'brand': 'Anessa',
    'type': 'chống nắng',
    'price': 495000,
    'image': 'https://example.com/image198.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP199',
    'name': 'Tẩy trang L’Oreal Micellar Water Deep Cleansing',
    'brand': 'L’Oreal',
    'type': 'tẩy trang',
    'price': 145000,
    'image': 'https://example.com/image199.jpg',
    'promotion': null,
  },
  {
    'id': 'SP200',
    'name': 'Serum The Inkey List Caffeine Eye Cream',
    'brand': 'The Inkey List',
    'type': 'serum',
    'price': 295000,
    'image': 'https://example.com/image200.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP201',
    'name': 'Son môi MAC Matte Lipstick',
    'brand': 'MAC',
    'type': 'son',
    'category': 'Makeup',
    'price': 520000,
    'image': 'https://example.com/image201.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP202',
    'name': 'Phấn phủ Maybelline Fit Me',
    'brand': 'Maybelline',
    'type': 'phấn phủ',
    'category': 'Makeup',
    'price': 230000,
    'image': 'https://example.com/image202.jpg',
    'promotion': null,
  },
  {
    'id': 'SP203',
    'name': 'Kem nền L’Oreal Infallible',
    'brand': 'L’Oreal',
    'type': 'kem nền',
    'category': 'Makeup',
    'price': 295000,
    'image': 'https://example.com/image203.jpg',
    'promotion': 'Tặng cọ nền',
  },
  {
    'id': 'SP204',
    'name': 'Mascara Maybelline Lash Sensational',
    'brand': 'Maybelline',
    'type': 'mascara',
    'category': 'Makeup',
    'price': 175000,
    'image': 'https://example.com/image204.jpg',
    'promotion': null,
  },
  {
    'id': 'SP205',
    'name': 'Kẻ mắt nước NYX Epic Ink',
    'brand': 'NYX',
    'type': 'kẻ mắt',
    'category': 'Makeup',
    'price': 165000,
    'image': 'https://example.com/image205.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP206',
    'name': 'Son dưỡng môi Laneige Lip Glowy Balm',
    'brand': 'Laneige',
    'type': 'son',
    'category': 'Makeup',
    'price': 220000,
    'image': 'https://example.com/image206.jpg',
    'promotion': null,
  },
  {
    'id': 'SP207',
    'name': 'Phấn phủ Innisfree No Sebum',
    'brand': 'Innisfree',
    'type': 'phấn phủ',
    'category': 'Makeup',
    'price': 150000,
    'image': 'https://example.com/image207.jpg',
    'promotion': 'Tặng gương mini',
  },
  {
    'id': 'SP208',
    'name': 'Kem nền Maybelline Super Stay',
    'brand': 'Maybelline',
    'type': 'kem nền',
    'category': 'Makeup',
    'price': 310000,
    'image': 'https://example.com/image208.jpg',
    'promotion': null,
  },
  {
    'id': 'SP209',
    'name': 'Mascara L’Oreal Voluminous',
    'brand': 'L’Oreal',
    'type': 'mascara',
    'category': 'Makeup',
    'price': 185000,
    'image': 'https://example.com/image209.jpg',
    'promotion': 'Giảm 15%',
  },
  {
    'id': 'SP210',
    'name': 'Kẻ mắt gel Bobbi Brown Long-Wear',
    'brand': 'Bobbi Brown',
    'type': 'kẻ mắt',
    'category': 'Makeup',
    'price': 480000,
    'image': 'https://example.com/image210.jpg',
    'promotion': null,
  },
  {
    'id': 'SP211',
    'name': 'Son kem lì 3CE Velvet Lip Tint',
    'brand': '3CE',
    'type': 'son',
    'category': 'Makeup',
    'price': 290000,
    'image': 'https://example.com/image211.jpg',
    'promotion': 'Mua 2 tặng 1',
  },
  {
    'id': 'SP212',
    'name': 'Phấn phủ Chanel Poudre Universelle',
    'brand': 'Chanel',
    'type': 'phấn phủ',
    'category': 'Makeup',
    'price': 1450000,
    'image': 'https://example.com/image212.jpg',
    'promotion': null,
  },
  {
    'id': 'SP213',
    'name': 'Kem nền NARS Natural Radiant',
    'brand': 'NARS',
    'type': 'kem nền',
    'category': 'Makeup',
    'price': 1350000,
    'image': 'https://example.com/image213.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP214',
    'name': 'Mascara Benefit They’re Real!',
    'brand': 'Benefit',
    'type': 'mascara',
    'category': 'Makeup',
    'price': 520000,
    'image': 'https://example.com/image214.jpg',
    'promotion': null,
  },
  {
    'id': 'SP215',
    'name': 'Kẻ mắt dạng bút Clio Sharp So Simple',
    'brand': 'Clio',
    'type': 'kẻ mắt',
    'category': 'Makeup',
    'price': 210000,
    'image': 'https://example.com/image215.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP216',
    'name': 'Son dưỡng Dior Addict Lip Glow',
    'brand': 'Dior',
    'type': 'son',
    'category': 'Makeup',
    'price': 850000,
    'image': 'https://example.com/image216.jpg',
    'promotion': null,
  },
  {
    'id': 'SP217',
    'name': 'Phấn phủ The Face Shop Oil Clear',
    'brand': 'The Face Shop',
    'type': 'phấn phủ',
    'category': 'Makeup',
    'price': 170000,
    'image': 'https://example.com/image217.jpg',
    'promotion': 'Giảm 20%',
  },
  {
    'id': 'SP218',
    'name': 'Kem nền Estee Lauder Double Wear',
    'brand': 'Estee Lauder',
    'type': 'kem nền',
    'category': 'Makeup',
    'price': 1450000,
    'image': 'https://example.com/image218.jpg',
    'promotion': null,
  },
  {
    'id': 'SP219',
    'name': 'Mascara Etude House Curl Fix',
    'brand': 'Etude House',
    'type': 'mascara',
    'category': 'Makeup',
    'price': 195000,
    'image': 'https://example.com/image219.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP220',
    'name': 'Kẻ mắt nước Maybelline Hyper Sharp',
    'brand': 'Maybelline',
    'type': 'kẻ mắt',
    'category': 'Makeup',
    'price': 160000,
    'image': 'https://example.com/image220.jpg',
    'promotion': null,
  },
  {
    'id': 'SP221',
    'name': 'Dầu gội Dove Nutritive Solutions',
    'brand': 'Dove',
    'type': 'dầu gội',
    'category': 'Haircare',
    'price': 95000,
    'image': 'https://example.com/image221.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP222',
    'name': 'Dầu xả Dove Intense Repair',
    'brand': 'Dove',
    'type': 'dầu xả',
    'category': 'Haircare',
    'price': 98000,
    'image': 'https://example.com/image222.jpg',
    'promotion': null,
  },
  {
    'id': 'SP223',
    'name': 'Xịt dưỡng tóc TRESemmé Keratin Smooth',
    'brand': 'TRESemmé',
    'type': 'xịt dưỡng tóc',
    'category': 'Haircare',
    'price': 145000,
    'image': 'https://example.com/image223.jpg',
    'promotion': 'Tặng lược gỡ rối',
  },
  {
    'id': 'SP224',
    'name': 'Kem ủ tóc L’Oreal Total Repair 5',
    'brand': 'L’Oreal',
    'type': 'kem ủ tóc',
    'category': 'Haircare',
    'price': 165000,
    'image': 'https://example.com/image224.jpg',
    'promotion': null,
  },
  {
    'id': 'SP225',
    'name': 'Dầu gội Head & Shoulders Cool Menthol',
    'brand': 'Head & Shoulders',
    'type': 'dầu gội',
    'category': 'Haircare',
    'price': 89000,
    'image': 'https://example.com/image225.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP226',
    'name': 'Dầu xả Pantene Pro-V',
    'brand': 'Pantene',
    'type': 'dầu xả',
    'category': 'Haircare',
    'price': 92000,
    'image': 'https://example.com/image226.jpg',
    'promotion': null,
  },
  {
    'id': 'SP227',
    'name': 'Xịt dưỡng tóc Mise En Scene Perfect Serum',
    'brand': 'Mise En Scene',
    'type': 'xịt dưỡng tóc',
    'category': 'Haircare',
    'price': 175000,
    'image': 'https://example.com/image227.jpg',
    'promotion': 'Giảm 15%',
  },
  {
    'id': 'SP228',
    'name': 'Kem ủ tóc Tsubaki Premium Repair Mask',
    'brand': 'Tsubaki',
    'type': 'kem ủ tóc',
    'category': 'Haircare',
    'price': 210000,
    'image': 'https://example.com/image228.jpg',
    'promotion': null,
  },
  {
    'id': 'SP229',
    'name': 'Dầu gội Sunsilk Smooth & Manageable',
    'brand': 'Sunsilk',
    'type': 'dầu gội',
    'category': 'Haircare',
    'price': 75000,
    'image': 'https://example.com/image229.jpg',
    'promotion': 'Tặng 1 mặt nạ tóc',
  },
  {
    'id': 'SP230',
    'name': 'Dầu xả Sunsilk Soft & Smooth',
    'brand': 'Sunsilk',
    'type': 'dầu xả',
    'category': 'Haircare',
    'price': 78000,
    'image': 'https://example.com/image230.jpg',
    'promotion': null,
  },
  {
    'id': 'SP231',
    'name': 'Xịt dưỡng tóc Lucido-L Hair Treatment Oil',
    'brand': 'Lucido-L',
    'type': 'xịt dưỡng tóc',
    'category': 'Haircare',
    'price': 185000,
    'image': 'https://example.com/image231.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP232',
    'name': 'Kem ủ tóc Watsons Argan Oil Hair Mask',
    'brand': 'Watsons',
    'type': 'kem ủ tóc',
    'category': 'Haircare',
    'price': 95000,
    'image': 'https://example.com/image232.jpg',
    'promotion': null,
  },
  {
    'id': 'SP233',
    'name': 'Dầu gội Rejoice Perfume Smooth',
    'brand': 'Rejoice',
    'type': 'dầu gội',
    'category': 'Haircare',
    'price': 69000,
    'image': 'https://example.com/image233.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP234',
    'name': 'Dầu xả Rejoice Rich Soft Smooth',
    'brand': 'Rejoice',
    'type': 'dầu xả',
    'category': 'Haircare',
    'price': 72000,
    'image': 'https://example.com/image234.jpg',
    'promotion': null,
  },
  {
    'id': 'SP235',
    'name': 'Xịt dưỡng tóc L’Oreal Extraordinary Oil',
    'brand': 'L’Oreal',
    'type': 'xịt dưỡng tóc',
    'category': 'Haircare',
    'price': 195000,
    'image': 'https://example.com/image235.jpg',
    'promotion': 'Tặng 1 mini size',
  },
  {
    'id': 'SP236',
    'name': 'Kem ủ tóc Moroccanoil Intense Hydrating Mask',
    'brand': 'Moroccanoil',
    'type': 'kem ủ tóc',
    'category': 'Haircare',
    'price': 650000,
    'image': 'https://example.com/image236.jpg',
    'promotion': null,
  },
  {
    'id': 'SP237',
    'name': 'Dầu gội OGX Biotin & Collagen',
    'brand': 'OGX',
    'type': 'dầu gội',
    'category': 'Haircare',
    'price': 210000,
    'image': 'https://example.com/image237.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP238',
    'name': 'Dầu xả OGX Argan Oil of Morocco',
    'brand': 'OGX',
    'type': 'dầu xả',
    'category': 'Haircare',
    'price': 215000,
    'image': 'https://example.com/image238.jpg',
    'promotion': null,
  },
  {
    'id': 'SP239',
    'name': 'Xịt dưỡng tóc Schwarzkopf Gliss Hair Repair',
    'brand': 'Schwarzkopf',
    'type': 'xịt dưỡng tóc',
    'category': 'Haircare',
    'price': 185000,
    'image': 'https://example.com/image239.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP240',
    'name': 'Kem ủ tóc Garnier Fructis Hair Food',
    'brand': 'Garnier',
    'type': 'kem ủ tóc',
    'category': 'Haircare',
    'price': 165000,
    'image': 'https://example.com/image240.jpg',
    'promotion': null,
  },
  {
    'id': 'SP241',
    'name': 'Sữa tắm Dove Deep Moisture',
    'brand': 'Dove',
    'type': 'sữa tắm',
    'category': 'Bodycare',
    'price': 95000,
    'image': 'https://example.com/image241.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP242',
    'name': 'Dưỡng thể Vaseline Healthy White',
    'brand': 'Vaseline',
    'type': 'dưỡng thể',
    'category': 'Bodycare',
    'price': 115000,
    'image': 'https://example.com/image242.jpg',
    'promotion': null,
  },
  {
    'id': 'SP243',
    'name': 'Tẩy tế bào chết St. Ives Apricot Scrub',
    'brand': 'St. Ives',
    'type': 'tẩy tế bào chết body',
    'category': 'Bodycare',
    'price': 135000,
    'image': 'https://example.com/image243.jpg',
    'promotion': 'Tặng 1 khăn tắm',
  },
  {
    'id': 'SP244',
    'name': 'Kem chống nắng body Nivea Sun Protect & Moisture',
    'brand': 'Nivea',
    'type': 'kem chống nắng body',
    'category': 'Bodycare',
    'price': 165000,
    'image': 'https://example.com/image244.jpg',
    'promotion': null,
  },
  {
    'id': 'SP245',
    'name': 'Sữa tắm Lifebuoy Total 10',
    'brand': 'Lifebuoy',
    'type': 'sữa tắm',
    'category': 'Bodycare',
    'price': 75000,
    'image': 'https://example.com/image245.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP246',
    'name': 'Dưỡng thể The Body Shop Almond Milk',
    'brand': 'The Body Shop',
    'type': 'dưỡng thể',
    'category': 'Bodycare',
    'price': 290000,
    'image': 'https://example.com/image246.jpg',
    'promotion': null,
  },
  {
    'id': 'SP247',
    'name': 'Tẩy tế bào chết body Organic Shop Coffee Sugar',
    'brand': 'Organic Shop',
    'type': 'tẩy tế bào chết body',
    'category': 'Bodycare',
    'price': 95000,
    'image': 'https://example.com/image247.jpg',
    'promotion': 'Giảm 15%',
  },
  {
    'id': 'SP248',
    'name': 'Kem chống nắng body Banana Boat Ultra Sport',
    'brand': 'Banana Boat',
    'type': 'kem chống nắng body',
    'category': 'Bodycare',
    'price': 210000,
    'image': 'https://example.com/image248.jpg',
    'promotion': null,
  },
  {
    'id': 'SP249',
    'name': 'Sữa tắm Hazeline Matcha & Lựu đỏ',
    'brand': 'Hazeline',
    'type': 'sữa tắm',
    'category': 'Bodycare',
    'price': 68000,
    'image': 'https://example.com/image249.jpg',
    'promotion': 'Tặng 1 mặt nạ',
  },
  {
    'id': 'SP250',
    'name': 'Dưỡng thể Cetaphil Moisturizing Lotion',
    'brand': 'Cetaphil',
    'type': 'dưỡng thể',
    'category': 'Bodycare',
    'price': 185000,
    'image': 'https://example.com/image250.jpg',
    'promotion': null,
  },
  {
    'id': 'SP251',
    'name': 'Tẩy tế bào chết body Tree Hut Shea Sugar Scrub',
    'brand': 'Tree Hut',
    'type': 'tẩy tế bào chết body',
    'category': 'Bodycare',
    'price': 195000,
    'image': 'https://example.com/image251.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP252',
    'name': 'Kem chống nắng body Anessa Perfect UV Sunscreen',
    'brand': 'Anessa',
    'type': 'kem chống nắng body',
    'category': 'Bodycare',
    'price': 495000,
    'image': 'https://example.com/image252.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP253',
    'name': 'Sữa tắm Enchanteur Romantic',
    'brand': 'Enchanteur',
    'type': 'sữa tắm',
    'category': 'Bodycare',
    'price': 85000,
    'image': 'https://example.com/image253.jpg',
    'promotion': null,
  },
  {
    'id': 'SP254',
    'name': 'Dưỡng thể Hatomugi Skin Conditioner',
    'brand': 'Hatomugi',
    'type': 'dưỡng thể',
    'category': 'Bodycare',
    'price': 145000,
    'image': 'https://example.com/image254.jpg',
    'promotion': 'Tặng 1 chai mini',
  },
  {
    'id': 'SP255',
    'name': 'Tẩy tế bào chết body Cocoon Dak Lak Coffee',
    'brand': 'Cocoon',
    'type': 'tẩy tế bào chết body',
    'category': 'Bodycare',
    'price': 165000,
    'image': 'https://example.com/image255.jpg',
    'promotion': null,
  },
  {
    'id': 'SP256',
    'name': 'Kem chống nắng body Vichy Ideal Soleil',
    'brand': 'Vichy',
    'type': 'kem chống nắng body',
    'category': 'Bodycare',
    'price': 520000,
    'image': 'https://example.com/image256.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP257',
    'name': 'Sữa tắm Purité Lavender',
    'brand': 'Purité',
    'type': 'sữa tắm',
    'category': 'Bodycare',
    'price': 78000,
    'image': 'https://example.com/image257.jpg',
    'promotion': null,
  },
  {
    'id': 'SP258',
    'name': 'Dưỡng thể Nivea Extra White Firming',
    'brand': 'Nivea',
    'type': 'dưỡng thể',
    'category': 'Bodycare',
    'price': 125000,
    'image': 'https://example.com/image258.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP259',
    'name': 'Tẩy tế bào chết body The Body Shop Mango',
    'brand': 'The Body Shop',
    'type': 'tẩy tế bào chết body',
    'category': 'Bodycare',
    'price': 295000,
    'image': 'https://example.com/image259.jpg',
    'promotion': null,
  },
  {
    'id': 'SP260',
    'name': 'Kem chống nắng body Biore UV Aqua Rich',
    'brand': 'Biore',
    'type': 'kem chống nắng body',
    'category': 'Bodycare',
    'price': 185000,
    'image': 'https://example.com/image260.jpg',
    'promotion': 'Tặng 1 túi chống nắng',
  },
  {
    'id': 'SP261',
    'name': 'Nước hoa Chanel Coco Mademoiselle',
    'brand': 'Chanel',
    'type': 'nước hoa',
    'category': 'Fragrance',
    'price': 2950000,
    'image': 'https://example.com/image261.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP262',
    'name': 'Xịt thơm Bath & Body Works Japanese Cherry Blossom',
    'brand': 'Bath & Body Works',
    'type': 'xịt thơm',
    'category': 'Fragrance',
    'price': 320000,
    'image': 'https://example.com/image262.jpg',
    'promotion': null,
  },
  {
    'id': 'SP263',
    'name': 'Nước hoa Dior Sauvage Eau de Toilette',
    'brand': 'Dior',
    'type': 'nước hoa',
    'category': 'Fragrance',
    'price': 2850000,
    'image': 'https://example.com/image263.jpg',
    'promotion': 'Tặng 1 mini size',
  },
  {
    'id': 'SP264',
    'name': 'Xịt thơm Victoria’s Secret Love Spell',
    'brand': 'Victoria’s Secret',
    'type': 'xịt thơm',
    'category': 'Fragrance',
    'price': 295000,
    'image': 'https://example.com/image264.jpg',
    'promotion': null,
  },
  {
    'id': 'SP265',
    'name': 'Nước hoa Gucci Bloom Eau de Parfum',
    'brand': 'Gucci',
    'type': 'nước hoa',
    'category': 'Fragrance',
    'price': 3150000,
    'image': 'https://example.com/image265.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP266',
    'name': 'Xịt thơm The Body Shop White Musk',
    'brand': 'The Body Shop',
    'type': 'xịt thơm',
    'category': 'Fragrance',
    'price': 350000,
    'image': 'https://example.com/image266.jpg',
    'promotion': null,
  },
  {
    'id': 'SP267',
    'name': 'Nước hoa Versace Bright Crystal',
    'brand': 'Versace',
    'type': 'nước hoa',
    'category': 'Fragrance',
    'price': 2650000,
    'image': 'https://example.com/image267.jpg',
    'promotion': 'Giảm 15%',
  },
  {
    'id': 'SP268',
    'name': 'Xịt thơm Innisfree Perfumed Body Mist Peach',
    'brand': 'Innisfree',
    'type': 'xịt thơm',
    'category': 'Fragrance',
    'price': 180000,
    'image': 'https://example.com/image268.jpg',
    'promotion': null,
  },
  {
    'id': 'SP269',
    'name': 'Nước hoa Calvin Klein CK One',
    'brand': 'Calvin Klein',
    'type': 'nước hoa',
    'category': 'Fragrance',
    'price': 1950000,
    'image': 'https://example.com/image269.jpg',
    'promotion': 'Tặng 1 túi du lịch',
  },
  {
    'id': 'SP270',
    'name': 'Xịt thơm Malissa Kiss Sweet Vanilla',
    'brand': 'Malissa Kiss',
    'type': 'xịt thơm',
    'category': 'Fragrance',
    'price': 145000,
    'image': 'https://example.com/image270.jpg',
    'promotion': null,
  },
  {
    'id': 'SP271',
    'name': 'Nước hoa Jo Malone English Pear & Freesia',
    'brand': 'Jo Malone',
    'type': 'nước hoa',
    'category': 'Fragrance',
    'price': 3450000,
    'image': 'https://example.com/image271.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP272',
    'name': 'Xịt thơm Enchanteur Charming',
    'brand': 'Enchanteur',
    'type': 'xịt thơm',
    'category': 'Fragrance',
    'price': 95000,
    'image': 'https://example.com/image272.jpg',
    'promotion': null,
  },
  {
    'id': 'SP273',
    'name': 'Nước hoa Lancome La Vie Est Belle',
    'brand': 'Lancome',
    'type': 'nước hoa',
    'category': 'Fragrance',
    'price': 3250000,
    'image': 'https://example.com/image273.jpg',
    'promotion': 'Tặng 1 túi mỹ phẩm',
  },
  {
    'id': 'SP274',
    'name': 'Xịt thơm Purité Lavender Body Mist',
    'brand': 'Purité',
    'type': 'xịt thơm',
    'category': 'Fragrance',
    'price': 125000,
    'image': 'https://example.com/image274.jpg',
    'promotion': null,
  },
  {
    'id': 'SP275',
    'name': 'Nước hoa Bvlgari Omnia Amethyste',
    'brand': 'Bvlgari',
    'type': 'nước hoa',
    'category': 'Fragrance',
    'price': 2750000,
    'image': 'https://example.com/image275.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP276',
    'name': 'Xịt thơm Evoluderm Body Mist Monoï',
    'brand': 'Evoluderm',
    'type': 'xịt thơm',
    'category': 'Fragrance',
    'price': 165000,
    'image': 'https://example.com/image276.jpg',
    'promotion': null,
  },
  {
    'id': 'SP277',
    'name': 'Nước hoa Elizabeth Arden Green Tea',
    'brand': 'Elizabeth Arden',
    'type': 'nước hoa',
    'category': 'Fragrance',
    'price': 1450000,
    'image': 'https://example.com/image277.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP278',
    'name': 'Xịt thơm Love Beauty and Planet Body Mist Coconut',
    'brand': 'Love Beauty and Planet',
    'type': 'xịt thơm',
    'category': 'Fragrance',
    'price': 175000,
    'image': 'https://example.com/image278.jpg',
    'promotion': null,
  },
  {
    'id': 'SP279',
    'name': 'Nước hoa Narciso Rodriguez For Her',
    'brand': 'Narciso Rodriguez',
    'type': 'nước hoa',
    'category': 'Fragrance',
    'price': 3550000,
    'image': 'https://example.com/image279.jpg',
    'promotion': 'Tặng 1 hộp quà',
  },
  {
    'id': 'SP280',
    'name': 'Xịt thơm Skin1004 Madagascar Centella Body Mist',
    'brand': 'Skin1004',
    'type': 'xịt thơm',
    'category': 'Fragrance',
    'price': 195000,
    'image': 'https://example.com/image280.jpg',
    'promotion': null,
  },
  {
    'id': 'SP281',
    'name': 'Bộ cọ trang điểm Real Techniques Everyday Essentials',
    'brand': 'Real Techniques',
    'type': 'cọ trang điểm',
    'category': 'Tools',
    'price': 520000,
    'image': 'https://example.com/image281.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP282',
    'name': 'Bông tẩy trang Silcot Premium Cotton',
    'brand': 'Silcot',
    'type': 'bông tẩy trang',
    'category': 'Tools',
    'price': 45000,
    'image': 'https://example.com/image282.jpg',
    'promotion': null,
  },
  {
    'id': 'SP283',
    'name': 'Máy rửa mặt Foreo Luna Mini 2',
    'brand': 'Foreo',
    'type': 'dụng cụ skincare',
    'category': 'Tools',
    'price': 2350000,
    'image': 'https://example.com/image283.jpg',
    'promotion': 'Tặng gel rửa mặt',
  },
  {
    'id': 'SP284',
    'name': 'Cọ trang điểm Vacosi Pro Brush Set',
    'brand': 'Vacosi',
    'type': 'cọ trang điểm',
    'category': 'Tools',
    'price': 395000,
    'image': 'https://example.com/image284.jpg',
    'promotion': null,
  },
  {
    'id': 'SP285',
    'name': 'Bông tẩy trang Ipek Cotton Pads',
    'brand': 'Ipek',
    'type': 'bông tẩy trang',
    'category': 'Tools',
    'price': 35000,
    'image': 'https://example.com/image285.jpg',
    'promotion': 'Mua 2 tặng 1',
  },
  {
    'id': 'SP286',
    'name': 'Dụng cụ massage mặt đá ngọc bích',
    'brand': 'Jade Roller',
    'type': 'dụng cụ skincare',
    'category': 'Tools',
    'price': 165000,
    'image': 'https://example.com/image286.jpg',
    'promotion': null,
  },
  {
    'id': 'SP287',
    'name': 'Cọ tán nền E.L.F Ultimate Blending Brush',
    'brand': 'E.L.F',
    'type': 'cọ trang điểm',
    'category': 'Tools',
    'price': 185000,
    'image': 'https://example.com/image287.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP288',
    'name': 'Bông tẩy trang Miniso Cotton Pads',
    'brand': 'Miniso',
    'type': 'bông tẩy trang',
    'category': 'Tools',
    'price': 29000,
    'image': 'https://example.com/image288.jpg',
    'promotion': null,
  },
  {
    'id': 'SP289',
    'name': 'Máy hút mụn Xiaomi InFace',
    'brand': 'Xiaomi',
    'type': 'dụng cụ skincare',
    'category': 'Tools',
    'price': 495000,
    'image': 'https://example.com/image289.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP290',
    'name': 'Cọ đánh mắt Morphe Eye Brush Set',
    'brand': 'Morphe',
    'type': 'cọ trang điểm',
    'category': 'Tools',
    'price': 620000,
    'image': 'https://example.com/image290.jpg',
    'promotion': null,
  },
  {
    'id': 'SP291',
    'name': 'Bông tẩy trang Lameila Cotton Puff',
    'brand': 'Lameila',
    'type': 'bông tẩy trang',
    'category': 'Tools',
    'price': 32000,
    'image': 'https://example.com/image291.jpg',
    'promotion': 'Tặng 1 túi zip',
  },
  {
    'id': 'SP292',
    'name': 'Dụng cụ massage nâng cơ mặt Refa Carat',
    'brand': 'Refa',
    'type': 'dụng cụ skincare',
    'category': 'Tools',
    'price': 3950000,
    'image': 'https://example.com/image292.jpg',
    'promotion': null,
  },
  {
    'id': 'SP293',
    'name': 'Cọ phủ phấn BH Cosmetics Large Powder Brush',
    'brand': 'BH Cosmetics',
    'type': 'cọ trang điểm',
    'category': 'Tools',
    'price': 215000,
    'image': 'https://example.com/image293.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP294',
    'name': 'Bông tẩy trang Guardian Soft Cotton',
    'brand': 'Guardian',
    'type': 'bông tẩy trang',
    'category': 'Tools',
    'price': 39000,
    'image': 'https://example.com/image294.jpg',
    'promotion': null,
  },
  {
    'id': 'SP295',
    'name': 'Máy xông mặt Kingdom KD-233',
    'brand': 'Kingdom',
    'type': 'dụng cụ skincare',
    'category': 'Tools',
    'price': 650000,
    'image': 'https://example.com/image295.jpg',
    'promotion': 'Tặng 1 mặt nạ giấy',
  },
  {
    'id': 'SP296',
    'name': 'Cọ má hồng FOCALLURE Blush Brush',
    'brand': 'FOCALLURE',
    'type': 'cọ trang điểm',
    'category': 'Tools',
    'price': 145000,
    'image': 'https://example.com/image296.jpg',
    'promotion': null,
  },
  {
    'id': 'SP297',
    'name': 'Bông tẩy trang Muji Cut Cotton',
    'brand': 'Muji',
    'type': 'bông tẩy trang',
    'category': 'Tools',
    'price': 85000,
    'image': 'https://example.com/image297.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP298',
    'name': 'Dụng cụ lăn lạnh mặt bằng thép không gỉ',
    'brand': 'Cool Roller',
    'type': 'dụng cụ skincare',
    'category': 'Tools',
    'price': 175000,
    'image': 'https://example.com/image298.jpg',
    'promotion': null,
  },
  {
    'id': 'SP299',
    'name': 'Cọ nền Wet n Wild Flat Top Brush',
    'brand': 'Wet n Wild',
    'type': 'cọ trang điểm',
    'category': 'Tools',
    'price': 95000,
    'image': 'https://example.com/image299.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP300',
    'name': 'Bông tẩy trang Emily Cotton Pads',
    'brand': 'Emily',
    'type': 'bông tẩy trang',
    'category': 'Tools',
    'price': 28000,
    'image': 'https://example.com/image300.jpg',
    'promotion': null,
  },
  {
    'id': 'SP301',
    'name': 'Viên uống đẹp da Blackmores Radiance',
    'brand': 'Blackmores',
    'type': 'thực phẩm chức năng',
    'category': 'Khác',
    'price': 450000,
    'image': 'https://example.com/image301.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP302',
    'name': 'Khẩu trang 3D Mask KF94',
    'brand': '3D Mask',
    'type': 'khẩu trang',
    'category': 'Khác',
    'price': 55000,
    'image': 'https://example.com/image302.jpg',
    'promotion': null,
  },
  {
    'id': 'SP303',
    'name': 'Nước súc miệng Listerine Cool Mint',
    'brand': 'Listerine',
    'type': 'nước súc miệng',
    'category': 'Khác',
    'price': 95000,
    'image': 'https://example.com/image303.jpg',
    'promotion': 'Tặng 1 chai mini',
  },
  {
    'id': 'SP304',
    'name': 'Dầu massage thư giãn Aroma Therapy',
    'brand': 'Aroma Therapy',
    'type': 'dầu massage',
    'category': 'Khác',
    'price': 165000,
    'image': 'https://example.com/image304.jpg',
    'promotion': null,
  },
  {
    'id': 'SP305',
    'name': 'Xịt khử mùi Nivea Men Cool Kick',
    'brand': 'Nivea',
    'type': 'xịt khử mùi',
    'category': 'Khác',
    'price': 115000,
    'image': 'https://example.com/image305.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP306',
    'name': 'Miếng dán mụn Cosrx Acne Pimple Master Patch',
    'brand': 'Cosrx',
    'type': 'miếng dán mụn',
    'category': 'Khác',
    'price': 75000,
    'image': 'https://example.com/image306.jpg',
    'promotion': null,
  },
  {
    'id': 'SP307',
    'name': 'Bộ quà tặng chăm sóc da Innisfree Holiday Set',
    'brand': 'Innisfree',
    'type': 'bộ quà tặng',
    'category': 'Khác',
    'price': 495000,
    'image': 'https://example.com/image307.jpg',
    'promotion': 'Tặng túi vải',
  },
  {
    'id': 'SP308',
    'name': 'Kem tẩy lông Veet Silk & Fresh',
    'brand': 'Veet',
    'type': 'tẩy lông',
    'category': 'Khác',
    'price': 95000,
    'image': 'https://example.com/image308.jpg',
    'promotion': null,
  },
  {
    'id': 'SP309',
    'name': 'Gel rửa tay khô Lifebuoy',
    'brand': 'Lifebuoy',
    'type': 'gel rửa tay',
    'category': 'Khác',
    'price': 35000,
    'image': 'https://example.com/image309.jpg',
    'promotion': 'Mua 2 tặng 1',
  },
  {
    'id': 'SP310',
    'name': 'Dung dịch vệ sinh phụ nữ Dạ Hương',
    'brand': 'Dạ Hương',
    'type': 'vệ sinh phụ nữ',
    'category': 'Khác',
    'price': 65000,
    'image': 'https://example.com/image310.jpg',
    'promotion': null,
  },
  {
    'id': 'SP311',
    'name': 'Viên uống trắng da Glutathione',
    'brand': 'Relumins',
    'type': 'thực phẩm chức năng',
    'category': 'Khác',
    'price': 620000,
    'image': 'https://example.com/image311.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP312',
    'name': 'Khẩu trang y tế 4 lớp',
    'brand': 'Ecom Med',
    'type': 'khẩu trang',
    'category': 'Khác',
    'price': 45000,
    'image': 'https://example.com/image312.jpg',
    'promotion': null,
  },
  {
    'id': 'SP313',
    'name': 'Nước súc miệng Colgate Plax',
    'brand': 'Colgate',
    'type': 'nước súc miệng',
    'category': 'Khác',
    'price': 89000,
    'image': 'https://example.com/image313.jpg',
    'promotion': 'Tặng bàn chải',
  },
  {
    'id': 'SP314',
    'name': 'Dầu massage body Purité',
    'brand': 'Purité',
    'type': 'dầu massage',
    'category': 'Khác',
    'price': 145000,
    'image': 'https://example.com/image314.jpg',
    'promotion': null,
  },
  {
    'id': 'SP315',
    'name': 'Xịt khử mùi Enchanteur Charming',
    'brand': 'Enchanteur',
    'type': 'xịt khử mùi',
    'category': 'Khác',
    'price': 95000,
    'image': 'https://example.com/image315.jpg',
    'promotion': 'Giảm 5%',
  },
  {
    'id': 'SP316',
    'name': 'Miếng dán mụn Some By Mi Clear Spot Patch',
    'brand': 'Some By Mi',
    'type': 'miếng dán mụn',
    'category': 'Khác',
    'price': 69000,
    'image': 'https://example.com/image316.jpg',
    'promotion': null,
  },
  {
    'id': 'SP317',
    'name': 'Bộ quà tặng Laneige Water Bank Set',
    'brand': 'Laneige',
    'type': 'bộ quà tặng',
    'category': 'Khác',
    'price': 850000,
    'image': 'https://example.com/image317.jpg',
    'promotion': 'Tặng túi đựng mỹ phẩm',
  },
  {
    'id': 'SP318',
    'name': 'Kem tẩy lông Palmer’s Cocoa Butter',
    'brand': 'Palmer’s',
    'type': 'tẩy lông',
    'category': 'Khác',
    'price': 115000,
    'image': 'https://example.com/image318.jpg',
    'promotion': null,
  },
  {
    'id': 'SP319',
    'name': 'Gel rửa tay khô On1',
    'brand': 'On1',
    'type': 'gel rửa tay',
    'category': 'Khác',
    'price': 42000,
    'image': 'https://example.com/image319.jpg',
    'promotion': 'Giảm 10%',
  },
  {
    'id': 'SP320',
    'name': 'Dung dịch vệ sinh phụ nữ Lactacyd',
    'brand': 'Lactacyd',
    'type': 'vệ sinh phụ nữ',
    'category': 'Khác',
    'price': 78000,
    'image': 'https://example.com/image320.jpg',
    'promotion': null,
  },
];

/// ✅ Hàm phân loại theo type
String getCategory(String type) {
  final typeLower = type.toLowerCase();
  if ([
    'chống nắng',
    'sữa rửa mặt',
    'serum',
    'toner',
    'kem dưỡng',
    'mặt nạ',
    'tẩy trang',
  ].contains(typeLower))
    return 'Skincare';

  if ([
    'son',
    'phấn phủ',
    'kem nền',
    'mascara',
    'kẻ mắt',
    'makeup remover',
  ].contains(typeLower))
    return 'Makeup';

  if (['dầu gội', 'dầu xả', 'xịt dưỡng tóc', 'kem ủ tóc'].contains(typeLower))
    return 'Haircare';

  if ([
    'sữa tắm',
    'dưỡng thể',
    'tẩy tế bào chết body',
    'kem chống nắng body',
  ].contains(typeLower))
    return 'Bodycare';

  if (['nước hoa', 'xịt thơm'].contains(typeLower)) return 'Fragrance';

  if ([
    'cọ trang điểm',
    'bông tẩy trang',
    'dụng cụ skincare',
  ].contains(typeLower))
    return 'Tools';

  return 'Khác';
}

/// ✅ Danh sách sản phẩm đã thêm category
final List<Map<String, dynamic>> productListt = productList.map((product) {
  final type = product['type'] as String? ?? '';
  final category = getCategory(type);
  return {...product, 'category': category};
}).toList();

final List<Map<String, dynamic>> productCategories = [
  {'label': 'Skincare', 'image': 'assets/skincare.jpg'},
  {'label': 'Makeup', 'image': 'assets/makeup.jpg'},
  {'label': 'Haircare', 'image': 'assets/haircare.jpg'},
  {'label': 'Bodycare', 'image': 'assets/bodycare.jpg'},
  {'label': 'Fragrance', 'image': 'assets/fragrance.jpg'},
  {'label': 'Tools', 'image': 'assets/tools.jpg'},
];
